import { index, countStats } from '../engine';
import './core';
import './generated';
import './life';
import './culture';
import './services';
import '../flights';
import '../flows';
import './packs/cities';
import './packs/cuisine';
import './packs/jobs';
import './packs/knowledge';
import './packs/everyday';
import './packs/calendar';
import './packs/homeculture';
import './packs/transport';
import './packs/workdays';
import './packs/infants';
import './packs/studentlife';
import './packs/rights';
import './packs/dacha';
import './packs/building';
import './packs/scams';
import './packs/sport';
import './packs/language';
import './packs/flat';
import './packs/payday';
import './packs/rail';
import './packs/school';
import './packs/emergency';
import './business';
import './arcs';
import './arcs2';
import './arcs3';
import './arcs4';
import './studies';
import './fines';
import './year';

index();

export { countStats };
