/* City guide pack: 37 cities × 12 scenarios (arrival, food, sight, quirk, market, transport, festival, jobs, story, day trip, university, street music). */
import { S, O } from '../../engine';
import type { State, Choice, Effects } from '../../engine';

const C = (t: string, msg: string, fx: Effects): Choice => ({ t, msg, fx });

// [name, nickname, landmark, food, quirk, day trip, main industry, university, festival]
const CITIES: [string, string, string, string, string, string, string, string, string][] = [
  ['Moscow', 'the capital', 'Red Square and the Kremlin', 'syrniki and kulebyaka', 'huge distances, rush-hour metro crowds and traffic jams', 'Sergiev Posad and its Trinity Lavra', 'finance, IT and services', 'Moscow State University', 'City Day in early September'],
  ['Saint Petersburg', 'the northern capital', 'the Hermitage and the Bronze Horseman', 'pyshki doughnuts and fried smelt', 'white nights in June and drawbridges that rise at night', 'Peterhof and its fountains', 'shipbuilding, port logistics and tourism', 'Saint Petersburg State University', 'Scarlet Sails graduation night'],
  ['Kazan', 'a city proud of its Tatar–Russian culture', 'the Kazan Kremlin', 'chak-chak and echpochmak', 'street signs in both Russian and Tatar', 'the island-town of Sviyazhsk', 'petrochemicals and the Innopolis IT town nearby', 'Kazan Federal University', 'Sabantuy, the plough festival'],
  ['Yekaterinburg', 'the capital of the Urals', 'the Church on the Blood and the Yeltsin Center', 'Ural pelmeni', 'a city founded on the edge of two continents', 'the Europe–Asia border obelisk', 'heavy industry and IT', 'Ural Federal University', 'the Stenograffia street-art festival'],
  ['Novosibirsk', 'the capital of Siberia', 'the Opera and Ballet Theatre, the largest theatre building in Russia', 'Siberian pelmeni with sour cream', 'beaches on the Ob river in summer and −30 °C in winter', 'the science town of Akademgorodok', 'science, IT and machine building', 'Novosibirsk State University', 'the Siberian jazz evenings'],
  ['Nizhny Novgorod', 'the city of the Volga and Oka', 'the Nizhny Novgorod Kremlin', 'Volga fish pies', 'a cable car that crosses the Volga to the town of Bor', 'the painted wooden houses of Gorodets', 'car plants and machine building', 'Lobachevsky University', 'River Day on the embankment'],
  ['Samara', 'the city on the Volga embankment', 'the long Volga embankment and Stalin\'s bunker', 'Volga fish soup and local beer', 'a very long embankment popular with cyclists', 'the Zhiguli hills', 'aerospace and engineering', 'Samara University', 'Cosmonautics Day'],
  ['Omsk', 'a Siberian city of Dostoevsky\'s exile', 'the Omsk Fortress and the Assumption Cathedral', 'Siberian pelmeni and river fish', 'hot summers and very cold winters', 'a river trip on the Irtysh', 'oil refining', 'Omsk State University', 'City Day in August'],
  ['Chelyabinsk', 'the city of steel and the 2013 meteorite', 'Kirovka, the pedestrian street', 'Ural pelmeni', 'factory smoke that colours some sunsets', 'Lake Turgoyak', 'metallurgy and tractors', 'South Ural State University', 'the Meteorite anniversary'],
  ['Rostov-on-Don', 'the gateway to the Caucasus', 'the Don embankment', 'Don fish and cherry vareniki', 'hot summers and Cossack songs', 'Taganrog, Chekhov\'s birthplace', 'agricultural machinery', 'Southern Federal University', 'the Cossack festival'],
  ['Ufa', 'the capital of Bashkortostan', 'the Salavat Yulaev monument above the Belaya river', 'Bashkir honey and kumys', 'Bashkir and Russian heard side by side', 'the Shulgan-Tash cave', 'oil refining and chemicals', 'Bashkir State University', 'the Yiyyn festival'],
  ['Krasnoyarsk', 'the city on the Yenisei', 'the Stolby nature reserve rock pillars', 'smoked fish and pine nuts', 'a river that stays unfrozen near the dam in winter', 'a hike among the Stolby rocks', 'aluminium and hydropower', 'Siberian Federal University', 'the Yenisei fair'],
  ['Perm', 'a city of art and the Urals', 'the Perm Art Gallery in the old cathedral', 'Perm "salted ears" jokes and fish pies', 'a city that gave its name to the Permian period in geology', 'the Kungur Ice Cave', 'oil, chemicals and machinery', 'Perm State University', 'the White Nights festival'],
  ['Voronezh', 'the cradle of the Russian navy', 'the Admiralty monument and the reservoir', 'dishes made from black-soil vegetables', 'fertile black-soil gardens', 'the chalk cliffs of Divnogorye', 'aviation and agriculture', 'Voronezh State University', 'the Platonov arts festival'],
  ['Volgograd', 'a city stretched along the Volga', 'Mamayev Kurgan and the Motherland Calls statue', 'Volga fish and Cossack dishes', 'a very long thin city along the river', 'a stretch of the Volga–Don canal', 'metallurgy and chemicals', 'Volgograd State University', 'Victory Day commemorations'],
  ['Krasnodar', 'the capital of Kuban', 'Galitsky Park and the stadium', 'Kuban borscht and fresh fruit', 'mild winters and a long warm autumn', 'the Black Sea coast', 'agriculture and retail headquarters', 'Kuban State University', 'the Kuban Cossack festival'],
  ['Sochi', 'the subtropical capital', 'the Olympic Park and Krasnaya Polyana', 'Black Sea tea and grilled fish', 'palm trees in a country famous for snow', 'the mountains of Krasnaya Polyana', 'tourism and hospitality', 'Sochi State University', 'the Kinotavr film festival'],
  ['Vladivostok', 'the Pacific capital', 'the Golden Bridge and the Russky Bridge', 'crab, scallops and sea kale', 'foggy summers and very steep streets', 'Russky Island', 'the port and shipping', 'Far Eastern Federal University', 'the Pacific Meridian film festival'],
  ['Grozny', 'a rebuilt city of glass towers', 'the Akhmad Kadyrov Mosque', 'zhizhig-galnash dumplings', 'new towers over a rebuilt city centre', 'the mountain lakes of Chechnya', 'oil and construction', 'Chechen State University', 'City Day in October'],
  ['Kaliningrad', 'a Russian exclave on the Baltic', 'Kant\'s tomb on Cathedral Island', 'marzipan and Baltic fish', 'a Russian region between Poland and Lithuania', 'the Curonian Spit', 'amber, ports and shipbuilding', 'Immanuel Kant Baltic Federal University', 'the Amber festival'],
  ['Saratov', 'a Volga city of cosmonauts', 'the Volga embankment', 'Saratov kalach bread', 'a long road bridge to the city of Engels', 'the town of Engels on the opposite bank', 'aviation and chemicals', 'Saratov State University', 'Cosmonautics Day, since Gagarin landed nearby'],
  ['Tyumen', 'the first Russian city in Siberia', 'the Tura river embankment', 'cedar-nut sweets and Siberian fish', 'neat streets thanks to oil and gas revenues', 'Tobolsk and its Siberian Kremlin', 'oil and gas', 'Tyumen State University', 'City Day, marking the 1586 founding'],
  ['Tolyatti', 'the city of Lada cars', 'the AvtoVAZ plant on the Volga', 'Volga fish soup', 'a city named after the Italian politician Palmiro Togliatti', 'the Zhiguli hills', 'the car industry', 'Tolyatti State University', 'the Lada fans\' day'],
  ['Izhevsk', 'a city of Kalashnikov and Udmurt culture', 'the Kalashnikov Museum', 'Udmurt-style pelmeni', 'Udmurt language alongside Russian', 'the town of Sarapul', 'machine building and arms', 'Udmurt State University', 'the Gerber plough festival'],
  ['Barnaul', 'the capital of Altai Krai', 'Demidov Square', 'Altai honey and mountain herbs', 'a ribbon of pine forest around the city', 'the spa town of Belokurikha', 'machine building and agriculture', 'Altai State University', 'the Altai honey fair'],
  ['Irkutsk', 'the gateway to Baikal', 'the wooden houses of the 130th quarter', 'smoked omul fish', 'the Angara river, which rarely freezes in the city', 'Listvyanka on Lake Baikal', 'aviation and hydropower', 'Irkutsk State University', 'Baikal Day'],
  ['Ulyanovsk', 'the birthplace of Lenin and of the writer Goncharov', 'the Lenin Memorial', 'Volga fish soup', 'two enormous bridges over the Volga', 'the cliffs along the Volga', 'aircraft building', 'Ulyanovsk State University', 'Goncharov Day'],
  ['Khabarovsk', 'a city on the Amur', 'the Amur bridge', 'Far Eastern salmon and caviar', 'China visible across the river', 'a cruise on the Amur', 'machine building and timber', 'Pacific State University', 'Amur Day'],
  ['Yakutsk', 'one of the coldest big cities on Earth', 'the Mammoth Museum', 'stroganina, thinly shaved frozen fish', 'buildings on piles because of permafrost', 'the Lena Pillars', 'diamonds and mining', 'North-Eastern Federal University', 'the Ysyakh summer festival'],
  ['Murmansk', 'a city above the Arctic Circle', 'the Alyosha monument', 'Barents Sea cod and fish soup', 'a polar night in winter and a midnight sun in summer', 'the Arctic village of Teriberka', 'fishing, the port and nuclear icebreakers', 'Murmansk State Technical University', 'the Return of the Sun in January'],
  ['Arkhangelsk', 'a White Sea port', 'the Northern Dvina embankment', 'Pomor fish pies', 'white nights and northern lights', 'the Malye Korely wooden architecture museum', 'timber and shipbuilding', 'Northern Arctic Federal University', 'the Pomor fair'],
  ['Makhachkala', 'the capital of Dagestan on the Caspian', 'the central Juma Mosque', 'khinkal and chudu flatbread', 'dozens of languages spoken across Dagestan', 'ancient Derbent and the Sulak Canyon', 'fishing, trade and construction', 'Dagestan State University', 'the Day of Unity of the Peoples of Dagestan'],
  ['Tula', 'the city of samovars, guns and gingerbread', 'the Tula Kremlin', 'Tula gingerbread', 'a city close enough to Moscow for day trips', 'Yasnaya Polyana, Tolstoy\'s estate', 'metalworking and arms', 'Tula State University', 'the Samovar festival'],
  ['Yaroslavl', 'a Golden Ring city on the Volga', 'the Spassky Monastery', 'Volga fish and pies', 'a city on the meeting of the Volga and the Kotorosl', 'Rostov Veliky', 'engines and machinery', 'Demidov Yaroslavl State University', 'City Day, since the founding in 1010'],
  ['Vladimir', 'an ancient capital of Rus', 'the Golden Gate and the Assumption Cathedral', 'Vladimir cherries', 'white-stone churches around every corner', 'the town of Suzdal', 'machinery and food processing', 'Vladimir State University', 'the Cherry festival'],
  ['Pskov', 'a border city with a fortress', 'the Pskov Kremlin (Krom)', 'Pskov smelt', 'a border with Estonia and Latvia not far away', 'the Pechory Monastery and Izborsk fortress', 'electrical engineering', 'Pskov State University', 'the commemoration of the 1242 Battle on the Ice'],
  ['Veliky Novgorod', 'one of the oldest Russian cities', 'the Novgorod Kremlin and St Sophia Cathedral', 'pies with local berries', 'the Millennium of Russia monument', 'the Yuriev Monastery', 'chemicals and food processing', 'Yaroslav-the-Wise Novgorod State University', 'the Veche bell commemoration'],
];

for (const [n, nick, landmark, food, quirk, trip, industry, uni, fest] of CITIES) {
  const here = (s: State): boolean => s.city === n;
  const id = (k: string): string => `city-${n.toLowerCase().replace(/[^a-z]+/g, '-')}-${k}`;
  S({ id: id('walk'), cat: 'life', req: here, w: 0.7, title: `${n}: your first walk`, text: `You step out in ${n}, ${nick}. The first thing you notice: ${quirk}. Locals hurry past; a pigeon eyes your sandwich.`,
    choices: [C(`Walk toward ${landmark}`, `You follow the signs toward ${landmark} and lose track of time.`, { know: 1, stress: -6, energy: -6 }), C('Find a café and watch the street', 'A cup of tea and a good seat: the city comes to you.', { money: -300, stress: -4 })] });
  S({ id: id('food'), cat: 'food', req: here, w: 0.8, title: `Taste of ${n}: ${food}`, text: `A local says you cannot know ${n} until you try ${food}.`,
    choices: [C('Try it at a local café', `You taste ${food}. The waiter watches your face and grins.`, { money: -500, stress: -8, energy: 8, know: 1 }), C('Cook a version at home', 'The first try is a disaster; the second is edible; the third is a triumph.', { money: -300, know: 2, energy: 5 })] });
  S({ id: id('sight'), cat: 'culture', req: here, w: 0.8, title: `${n}: ${landmark}`, text: `The best-known sight of ${n} is ${landmark}. A local guide offers a short walking tour.`,
    choices: [C('Take the guided walk (₽600)', `The guide tells stories about ${landmark} that no signboard mentions.`, { money: -600, know: 3, merit: 2 }), C('Wander alone at your own pace', 'You get lost twice and find a perfect courtyard.', { know: 2, merit: 1, stress: -5 })] });
  S({ id: id('quirk'), cat: 'life', req: here, w: 0.6, title: `Life in ${n}: a local quirk`, text: `Everyday life in ${n} comes with a quirk: ${quirk}.`,
    choices: [C('Adapt and enjoy it', 'Within a week it feels normal; within a month you would miss it.', { know: 1, stress: -3 }), C('Complain to a friend', 'Your friend laughs: "Welcome to the club."', { stress: 2, friends: 0 })] });
  S({ id: id('market'), cat: 'shop', req: here, w: 0.6, title: `${n}: the local market`, text: `The market in ${n} sells ingredients for ${food}, woollen socks, honey and everything in between.`,
    choices: [C('Haggle for a bargain', 'You win ₽150 and lose five minutes of your life.', { money: -250, stress: -2 }), C('Pay the asking price and chat', 'The seller adds an apple "for the road".', { money: -400, rep: 1, stress: -4 })] });
  S({ id: id('transport'), cat: 'life', req: here, w: 0.6, title: `Getting around ${n}`, text: `In ${n} you can use public transport, a taxi app or your feet. A map app says 35 minutes.`,
    choices: [C('Take public transport (₽60–90)', 'Crowded but cheap; you read three pages of a novel.', { money: -90, energy: -3 }), C('Walk', 'The city looks different at walking speed.', { energy: -8, health: 1, stress: -4 })] });
  S({ id: id('fest'), cat: 'culture', req: here, w: 0.7, title: `${n}: ${fest}`, text: `This season locals in ${n} talk about one thing: ${fest}.`,
    choices: [C('Join in with neighbours', 'You end up dancing in a circle with strangers.', { money: -500, merit: 3, stress: -10, friends: 1 }), C('Watch from the side', 'You enjoy it from a safe distance.', { stress: -4, merit: 1 })] });
  S({ id: id('jobs'), cat: 'life', req: here, w: 0.6, title: `Jobs in ${n}`, text: `The biggest employers in ${n} are in ${industry}. A friend says a company is hiring.`,
    choices: [C('Ask about the vacancy', 'You get a phone number and a surprisingly honest description of the shifts.', { know: 1, rep: 1, stress: 2 }), C('Stay with your current plan', 'You nod and keep your options open.', {})] });
  S({ id: id('story'), cat: 'social', req: here, w: 0.6, title: `${n}: a local tells a story`, text: `At a bus stop in ${n}, an old man tells you why the city is known as ${nick}. He talks for twenty minutes without pausing.`,
    choices: [C('Listen carefully', 'You miss your bus, and you do not mind.', { know: 2, stress: -4, merit: 1 }), C('Nod and check the time', 'He shrugs: "Young people."', {})] });
  S({ id: id('trip'), cat: 'culture', req: here, w: 0.7, title: `${n}: day trip to ${trip}`, text: `A friend suggests a day trip to ${trip}. The bus leaves at 8:30.`,
    choices: [C('Go (₽1,500)', `You return tired, tanned and rich in stories about ${trip}.`, { money: -1500, stress: -12, know: 2, merit: 2, energy: -12 }), C('Stay in the city', 'A quiet day in the flat.', { energy: 8 })] });
  S({ id: id('uni'), cat: 'edu', req: here, w: 0.6, title: `${n}: open day at ${uni}`, text: `Open day at ${uni}: stands, professors and free tea. A student guides groups through the corridors.`,
    choices: [C('Attend and ask questions', 'You leave with leaflets, a sticker and a better plan.', { know: 3, stress: -2, energy: -6 }), C('Skip it', 'You read the programme online instead.', { know: 1 })] });
  S({ id: id('music'), cat: 'social', req: here, w: 0.5, title: `${n}: a street musician`, text: `On a pedestrian street in ${n}, a musician plays an accordion and sings an old song. People slow down.`,
    choices: [C('Stop and listen, tip ₽100', 'For three minutes the whole street feels like a family.', { money: -100, stress: -8, merit: 1 }), C('Walk on', 'The music follows you for a block.', {})] });
}
