/* Everyday-life pack: law and rights, technology, hobbies, faith and community, health, neighbourhood,
   life events, money and seasons. Each row is a hand-written situation with two choices. */
import { S, O } from '../../engine';
import type { Effects, State } from '../../engine';

type Pick2 = [label: string, msg: string, fx: Effects];
interface Opts { who?: string[]; months?: number[]; req?: (s: State) => unknown; w?: number; once?: boolean }
const R = (id: string, cat: string, title: string, text: string, a: Pick2, b: Pick2, o: Opts = {}): void => {
  S({ id: `ev-${id}`, cat, title, text, who: o.who, months: o.months, req: o.req, w: o.w ?? 1, once: o.once,
    choices: [{ t: a[0], r: () => O(a[1], a[2]) }, { t: b[0], r: () => O(b[1], b[2]) }] });
};
const foreignOnly = { who: ['foreigner'] };

/* =================== LAW AND RIGHTS =================== */
R('law1', 'life', 'Free legal aid', 'A notice at the community centre: "Free legal consultation on Wednesdays". A volunteer lawyer reads your problem and nods.', ['Go and ask about your rights', 'She explains in plain language and gives you a checklist. You feel less alone.', { know: 3, stress: -8, merit: 1 }], ['Try to solve it alone', 'It takes three weeks and a lot of reading.', { know: 1, stress: 6 }]);
R('law2', 'life', 'Inspector on the tram', 'A transport inspector asks for your ticket. You paid, but the receipt is in your other coat.', ['Show your payment in the app', 'The inspector checks and thanks you.', { stress: 2 }], ['Argue that you paid', 'He writes a fine of ₽500; you pay it, annoyed.', { money: -500, stress: 6 }]);
R('law3', 'paper', 'Unpaid wages, small claims', 'Your employer owes you a month of wages. A friend says: "Go to the court, it is free for small claims."', ['File a statement with the labour inspectorate', 'An officer calls the employer. The money arrives the next day.', { money: 4000, rep: 3, stress: -6, know: 2 }], ['Wait and hope', 'You wait. You keep waiting.', { stress: 8 }]);
R('law4', 'paper', 'Power of attorney', 'You need someone at home to act on your behalf in a property matter. A notary can draw up a power of attorney.', ['Visit a notary (₽2,500)', 'Stamp, signature, three copies. Done.', { money: -2500, energy: -6 }], ['Leave it unsolved', 'The matter drags on, and your relatives keep asking.', { stress: 6, famLove: -2 }]);
R('law5', 'paper', 'A debt notice', 'A letter from the bailiffs (FSSP) arrives with your name and a sum you do not recognise.', ['Check it on the official website and call', 'It is a mistake: a different person with the same name.', { stress: -4, know: 2 }], ['Ignore it', 'Three weeks later your card is blocked.', { stress: 12, money: -500 }]);
R('law6', 'life', 'A faulty kettle', 'The kettle you bought two weeks ago stops working. The shop assistant says "no returns".', ['Cite your consumer rights politely', 'The manager checks and replaces it.', { rep: 2, know: 2 }], ['Give up and buy another', 'You pay twice.', { money: -1500 }]);
R('law7', 'home', 'Neighbour\'s flood', 'Water drips from your ceiling. The flat upstairs belongs to someone who is away.', ['Call the management company for an official act', 'They come, document the damage and call the owner. Repairs are paid by the owner\'s insurance.', { know: 2, stress: 4, money: 800 }], ['Put a bucket under the leak', 'It works until the ceiling collapses.', { stress: 10, money: -2500 }]);
R('law8', 'paper', 'Read the employment contract', 'Your employer hands you a long contract and says "just sign here, everyone does".', ['Read it and ask about unclear points', 'You catch a clause about unpaid overtime and negotiate it out.', { know: 3, rep: 2, stress: 2 }], ['Sign without reading', 'It works out. Mostly.', { stress: 4 }]);
R('law9', 'life', 'Carry copies of your documents', 'A friend says: "Keep copies of your documents in your phone and a paper copy at home."', ['Scan everything now', 'It takes an hour, but you feel better prepared.', { know: 2, stress: -4, energy: -4 }], ['Leave it for later', 'Later does not come until something goes missing.', { stress: 2 }], { ...foreignOnly });
R('law10', 'paper', 'A court summons', 'A white envelope: "You are called as a witness in a case." Your hands are cold.', ['Go and tell what you saw', 'The judge is brisk, the lawyer polite. You are done in two hours.', { stress: 6, rep: 3, merit: 3, energy: -8 }], ['Ignore the summons', 'A second letter arrives, less friendly, with a fine.', { money: -2000, stress: 10 }]);
R('law11', 'paper', 'Recognition of a diploma', 'Your diploma from home must be recognised in Russia before you can work in your profession.', ['Submit it for recognition (₽5,000)', 'Months later: "Recognised." You are legal in your field.', { money: -5000, know: 3, stress: -4 }], ['Work in another field', 'Safer, but less satisfying.', { stress: 3 }], { ...foreignOnly });
R('law12', 'paper', 'Tax deduction for studies', 'You can claim back part of what you paid for education through the tax service portal.', ['File the form on the portal', 'A month later ₽8,000 arrives on your card.', { money: 8000, know: 2 }], ['Skip the paperwork', 'Free money stays unclaimed.', {}], { who: ['citizen'] });
R('law13', 'life', 'Name spelled differently', 'The airline, the bank and the MFC all spell your surname differently.', ['Gather documents and fix every record', 'It takes weeks, but your papers finally match.', { know: 2, stress: 6, energy: -10 }], ['Hope no one notices', 'Someone notices at the worst moment.', { stress: 6 }]);
R('law14', 'paper', 'Marriage name change', 'After the wedding you decide to change your surname in all documents.', ['Do the whole circuit: passport, bank, SNILS, driving licence', 'Three weeks of queues. Then everything is aligned.', { energy: -12, stress: 4, love: 3 }], ['Keep your name', 'Your partner nods. Simple.', {}], { req: s => !!s.flags.married });
R('law15', 'life', 'An inheritance', 'A distant relative has left you a small flat in a village. The paperwork looks terrifying.', ['Go to the notary within six months', 'It is a long process, but the flat is yours in the end.', { flag: 'villageFlat', money: -3000, stress: 6, know: 2 }], ['Ignore it', 'The right to inherit expires.', { stress: 4 }], { once: true, w: 0.4 });

/* =================== TECHNOLOGY =================== */
R('tech1', 'life', 'Gosuslugi login', 'The portal asks for an SMS code, then a password, then a code again. The app is "temporarily unavailable".', ['Try the mobile app', 'Fingerprint login works at once. The fancy new version is better than the old.', { stress: -4, know: 1 }], ['Go to the MFC in person', 'You wait for forty minutes and are told the system is back.', { energy: -8, stress: 5 }]);
R('tech2', 'life', 'Pay with a QR code', 'At the market a seller shows a QR code instead of a card machine.', ['Scan with your bank app', 'Instant payment, no cash needed. A babushka pays by QR too.', { stress: -2, know: 1 }], ['Pay in cash', 'The seller smiles and gives you change from a tin.', { money: -200 }]);
R('tech3', 'life', 'Lost SIM card', 'You change your SIM and discover that the bank codes still go to the old number.', ['Visit the bank branch to update your number', 'It takes an hour. The clerk is kind.', { energy: -8, stress: 3, know: 1 }], ['Wait until the old SIM expires', 'You cannot log in for three weeks.', { stress: 8 }]);
R('tech4', 'life', 'A message about a parcel', 'An SMS: "Your parcel is waiting. Pay ₽99 to receive it" with a link.', ['Do not click, check the post office app', 'No parcel is waiting. You report the number.', { rep: 1, know: 2 }], ['Click the link', 'The "payment page" steals your card data. Your balance drops.', { money: -Math.min(8000, 8000), stress: 14 }]);
R('tech5', 'life', 'The building chat', 'Your building has a messenger chat with 214 residents. Today: the heating, the lift and a disputed parking spot.', ['Join the discussion politely', 'You get thanked for a practical idea and invited to tea.', { rep: 3, friends: 1, stress: -2 }], ['Mute the chat', 'Silence. For a day.', { stress: -2 }]);
R('tech6', 'life', 'Electronic queue at the MFC', 'A touchscreen asks you to pick a service and prints a ticket: "B-217, estimated wait 1 h 20 min".', ['Pick the right service carefully', 'Your number is called after 35 minutes. Efficient.', { energy: -4, stress: -2 }], ['Choose the first option', 'Wrong queue. You start again.', { energy: -8, stress: 6 }]);
R('tech7', 'life', 'Voice assistant', 'You ask your phone assistant for directions. It understands your accent, mostly.', ['Repeat slowly and clearly', 'The assistant sends you to the right bus stop.', { stress: -2, know: 1 }], ['Type the address instead', 'Faster, but less fun.', {}]);
R('tech8', 'life', 'Online lecture lag', 'Your online class freezes and the teacher\'s voice turns into robot noise.', ['Reconnect and ask for the recording', 'The teacher shares the video. You catch up in the evening.', { know: 2, stress: 2 }], ['Skip the lecture', 'You miss an important announcement.', { know: -1, stress: 4 }]);
R('tech9', 'life', 'Telemedicine consultation', 'A doctor answers your chat within ten minutes and sends a prescription to your phone.', ['Accept the quick consultation (₽700)', 'It is a simple cold; a pharmacy delivers the medicine.', { money: -700, health: 4, stress: -3 }], ['Wait for a polyclinic appointment', 'You get a slot in two weeks.', { stress: 4 }]);
R('tech10', 'life', 'Digital signature', 'A freelance client sends a contract to sign with an electronic signature.', ['Set up an e-signature and sign', 'It takes fifteen minutes, then it works forever.', { know: 2, rep: 2 }], ['Print, sign and scan', 'Old-fashioned but works.', { energy: -4 }]);
R('tech11', 'life', 'Wi-Fi in the metro', 'Free Wi-Fi in the metro asks for your phone number and a code.', ['Use mobile data instead', 'You skip the sign-up and read your book offline.', { stress: -2 }], ['Register for the Wi-Fi', 'The connection drops at every station.', { stress: 3 }]);
R('tech12', 'life', 'A marketplace review', 'A seller on a marketplace has hundreds of five-star reviews, all from the same day.', ['Look for a seller with real reviews', 'You buy a bit more expensive but it arrives as described.', { money: -300, know: 2 }], ['Buy from the cheap seller', 'The item looks nothing like the photos.', { money: -1200, stress: 5 }]);
R('tech13', 'life', 'Smart intercom', 'The new intercom needs an app. The courier is shouting at the door.', ['Install it quickly and open the door', 'The courier thanks you. The app wants five permissions.', { know: 1, stress: 2 }], ['Walk down the stairs', 'Five floors. The courier is gone.', { energy: -6 }]);
R('tech14', 'life', 'Backup your documents', 'You realise all your documents are on one old phone.', ['Back up to the cloud and a USB drive', 'You sleep better.', { know: 2, stress: -4, energy: -4 }], ['Keep going without a backup', 'Nothing bad happens. Yet.', {}]);

/* =================== HOBBIES AND SPORT =================== */
R('hob1', 'social', 'Chess in the park', 'Old men play chess under a tree and watch every move with commentary.', ['Ask for a game', 'You lose in eleven moves and learn more than from a book.', { know: 2, rep: 2, stress: -6, friends: 1 }], ['Watch quietly', 'You learn the gambit without risking your pride.', { know: 1, stress: -4 }]);
R('hob2', 'social', 'Five-a-side football', 'A group asks if you want to join their Thursday evening game in a hall.', ['Say yes (₽300)', 'You play badly and enthusiastically. Beer and fish afterwards.', { money: -300, health: 2, stress: -10, friends: 1, energy: -10 }], ['Say no', 'They wave: "Next week!"', {}]);
R('hob3', 'social', 'Skating in the park', 'In winter the park fills with ice rinks, music and hot tea.', ['Rent skates (₽400)', 'You fall twice and glide once. A toddler overtakes you.', { money: -400, stress: -12, health: 1, energy: -8 }], ['Watch with a cup of tea', 'Steam and snow. You enjoy it from the bench.', { stress: -6 }], { months: [11, 12, 1, 2, 3] });
R('hob4', 'social', 'Ice fishing', 'A neighbour invites you to fish through a hole in the ice on a frozen lake.', ['Go with a thermos and warm boots', 'You catch two fish and a cold. The soup afterwards is magnificent.', { stress: -12, energy: -10, friends: 1, merit: 1 }], ['Stay home', 'You hear the stories afterwards.', {}], { months: [12, 1, 2, 3] });
R('hob5', 'social', 'Mushroom picking', 'A colleague invites you to the forest for the "silent hunt".', ['Go with an experienced picker', 'You find boletus and chanterelles and learn what not to touch.', { stress: -14, know: 2, energy: -10, health: 1 }], ['Stay in the city', 'Quiet weekend.', {}], { months: [8, 9, 10] });
R('hob6', 'social', 'Berry picking', 'Wild strawberries, blueberries and raspberries are ripe.', ['Fill a bucket', 'Jam for the winter and purple fingers.', { energy: -10, stress: -10, money: 400 }], ['Buy berries at the market', 'Easier but pricier.', { money: -600 }], { months: [7, 8] });
R('hob7', 'social', 'Choir rehearsal', 'The neighbourhood choir needs voices. You have a decent one, apparently.', ['Join the choir', 'Folk songs, Soviet hits and hymns. You leave humming.', { stress: -10, friends: 2, merit: 2 }], ['Listen from the back row', 'Beautiful sound; you almost cry.', { stress: -6 }]);
R('hob8', 'social', 'Guitar in the kitchen', 'A friend plays old bard songs on a guitar and everyone sings along.', ['Sing along', 'You do not know the words but you know the feeling.', { stress: -12, friends: 1 }], ['Request a song from your own country', 'They learn the chorus quickly.', { stress: -10, friends: 1, merit: 2 }]);
R('hob9', 'social', 'Board games café', 'A café with a thousand board games and a patient owner.', ['Learn a new game', 'Three hours pass as if they were ten minutes.', { money: -500, stress: -10, friends: 1, know: 1 }], ['Order tea and read', 'Quiet corner, warm light.', { money: -300, stress: -6 }]);
R('hob10', 'social', 'Language exchange', 'An evening where people swap languages: an hour of Russian, an hour of your language.', ['Join the evening', 'You make friends and learn two new idioms.', { know: 3, friends: 2, stress: -4 }], ['Skip it', 'You stay with your textbook.', { know: 1 }]);
R('hob11', 'social', 'Book club', 'A library club reads and argues about classics.', ['Join and bring your own favourite book', 'The debate over Anna Karenina goes on until the lights go out.', { know: 3, rep: 2, friends: 1 }], ['Read alone', 'Your own private book club of one.', { know: 2 }]);
R('hob12', 'social', 'Climbing wall', 'A friend drags you to a climbing gym.', ['Try it', 'Your forearms burn, your head clears.', { money: -600, health: 2, stress: -10, energy: -10 }], ['Watch from below', 'You admire the spiders.', {}]);
R('hob13', 'social', 'Folk dance class', 'A community centre teaches folk dances from across Russia and beyond.', ['Join a class (₽300)', 'You twirl, stomp and laugh. Everyone is kind to beginners.', { money: -300, stress: -12, friends: 2, merit: 2 }], ['Watch the rehearsal', 'The dancers\' costumes make you smile.', { stress: -4 }]);
R('hob14', 'social', 'Sambo club', 'A local club teaches the Russian martial art sambo.', ['Try a trial class', 'You are thrown on the mat, politely and repeatedly.', { health: 3, stress: -8, energy: -12, friends: 1 }], ['Watch a class', 'You decide it looks very hard.', {}]);
R('hob15', 'social', 'Swimming pool certificate', 'The pool wants a health certificate. A polyclinic queue is the price of a swim.', ['Get the certificate and swim', 'A kilometre in the pool makes you feel like a new person.', { money: -800, health: 3, stress: -10, energy: -8 }], ['Skip swimming', 'You sit by the pool café instead.', { money: -200 }]);
R('hob16', 'social', 'Hackathon', 'A weekend hackathon at a local university. Pizza, laptops and fierce teams.', ['Join a team', 'You help build a small app for your neighbourhood and win a mug.', { know: 4, friends: 2, energy: -18, merit: 3 }], ['Visit for the pizza only', 'Not bad pizza.', { stress: -3 }]);
R('hob17', 'social', 'Hiking in Karelia', 'A group of friends plans a weekend by lakes and pine forests.', ['Go (₽4,000)', 'Tents, campfire and a sky with too many stars.', { money: -4000, stress: -16, energy: -12, friends: 1, merit: 1 }], ['Skip it', 'You hear about the mosquitos afterwards.', {}], { months: [6, 7, 8] });
R('hob18', 'social', 'Embroidery circle', 'The grandmothers of the neighbourhood meet to knit, embroider and gossip.', ['Join them', 'Your first row is crooked, your first scarf is long. They adopt you.', { stress: -10, friends: 1, rep: 3, merit: 1 }], ['Offer to carry the tea', 'You get a plate of pirozhki and a seat.', { stress: -6, rep: 2 }]);
R('hob19', 'social', 'Photo walk', 'Photographers meet to walk through old courtyards at golden hour.', ['Join with your phone camera', 'You find a doorway that looks like a painting.', { stress: -8, know: 1, friends: 1 }], ['Walk alone with headphones', 'You take forty photos of one lamp post.', { stress: -4 }]);
R('hob20', 'social', 'Amateur theatre', 'The community drama club needs actors for a village play.', ['Audition', 'You get the role of the third peasant. You are brilliant.', { know: 1, friends: 2, stress: -8, merit: 2 }], ['Help with the scenery', 'You paint a tree for six hours and love it.', { stress: -6, merit: 2 }]);

/* =================== FAITH AND COMMUNITY =================== */
R('faith1', 'culture', 'Friday prayer and a shared lunch', 'A mosque in the city invites the neighbourhood for a community lunch after the prayer.', ['Join the lunch', 'Plov, flatbread and tea. The imam asks about your family.', { stress: -10, friends: 2, merit: 2 }], ['Pass by respectfully', 'The smell of food follows you home.', { stress: -2 }]);
R('faith2', 'culture', 'An Orthodox liturgy', 'The church bells ring on a Sunday morning. Candles flicker, a choir sings.', ['Stand quietly at the back', 'The singing carries you away. Nobody minds that you are only watching.', { stress: -12, know: 1, merit: 1 }], ['Walk around the church garden', 'A kind old woman gives you a rusk and a smile.', { stress: -6 }]);
R('faith3', 'culture', 'A Buddhist datsan', 'In a Buddhist temple, monks chant, prayer wheels spin and visitors walk clockwise.', ['Visit respectfully and turn the wheels', 'A monk shows you how to spin them. You leave calm.', { stress: -14, know: 2, merit: 1 }], ['Take photos from the gate', 'A sign asks politely not to.', { stress: -2 }], { w: 0.5 });
R('faith4', 'culture', 'Shabbat dinner', 'A Jewish community invites guests for a Friday night dinner.', ['Accept the invitation', 'Candles, bread, songs, jokes. You are asked a hundred questions.', { stress: -10, friends: 2, know: 2, merit: 1 }], ['Thank them and decline', 'They promise a plate for next time.', {}], { w: 0.5 });
R('faith5', 'culture', 'Iftar during Ramadan', 'A neighbour from Dagestan invites you to break the fast at sunset.', ['Join at sunset', 'Dates, soup, bread and a long conversation about patience.', { stress: -10, friends: 2, rep: 3, merit: 2 }], ['Bring a gift of fruit', 'It is gratefully accepted.', { money: -400, rep: 2 }], { w: 0.5 });
R('faith6', 'culture', 'Epiphany ice-hole swim', 'On 19 January many Orthodox believers dip in an ice hole cut in a river or lake.', ['Watch with a flask of tea', 'Steam rises from brave swimmers. You applaud.', { stress: -6, merit: 1 }], ['Take the plunge', 'Three seconds of terror, three hours of glow.', { stress: -14, health: 2, merit: 2 }], { months: [1] });
R('faith7', 'culture', 'Christmas carols', 'Children go from door to door singing carols for sweets.', ['Open the door and give sweets', 'They sing off-key and sweetly.', { money: -100, stress: -8, merit: 1 }], ['Pretend not to be home', 'Disappointed voices drift away.', {}], { months: [1] });
R('faith8', 'culture', 'Apple Spas', 'On 19 August Orthodox communities bless the first apples of the season.', ['Take a bag of apples to be blessed', 'Everyone shares them afterwards.', { stress: -8, rep: 2, merit: 1 }], ['Buy apples at the market', 'Crisp, sweet and cheap.', { money: -250 }], { months: [8] });

/* =================== HEALTH =================== */
R('hl1', 'health', 'Flu shot', 'The polyclinic offers a free flu vaccination in autumn.', ['Get vaccinated', 'A small pinch and a sticker: "I was brave."', { health: 3 }], ['Skip it', 'You catch the flu in November.', { health: -8, energy: -12 }], { months: [9, 10, 11] });
R('hl2', 'health', 'Birch pollen allergy', 'Birches bloom and your nose runs like a tap.', ['Buy antihistamines (₽500)', 'You can breathe, mostly.', { money: -500, health: 2 }], ['Endure it', 'Two weeks of sneezing.', { health: -3, stress: 5 }], { months: [4, 5] });
R('hl3', 'health', 'A tick bite', 'After a walk in the forest you find a tick on your leg.', ['Go to the emergency room to remove it', 'They remove it and advise about the vaccine.', { health: 1, stress: 3, know: 1 }], ['Pull it out yourself', 'You manage, with trembling hands.', { stress: 6, health: -2 }], { months: [5, 6, 7, 8] });
R('hl4', 'health', 'Heat wave', 'Thirty-five degrees in the shade and no air conditioning.', ['Drink water and stay indoors', 'You survive with a wet towel and a book.', { stress: 2 }], ['Walk in the midday sun', 'Dizziness, headache and a very long nap.', { health: -5, energy: -12 }], { months: [7, 8] });
R('hl5', 'health', 'Sleepless nights', 'You cannot sleep. The white nights, the stress and the noise do not help.', ['Set a routine and cut screens', 'It works, slowly.', { health: 2, stress: -6, energy: 8 }], ['Scroll until dawn', 'You are a zombie all day.', { energy: -14, stress: 6 }]);
R('hl6', 'health', 'Back pain', 'Lifting boxes has left you with a sore back.', ['See a physiotherapist (₽2,000)', 'Exercises, heat and advice. It helps.', { money: -2000, health: 4 }], ['Take painkillers', 'The pain returns after a day.', { money: -300, health: -2 }]);
R('hl7', 'health', 'A first-aid course', 'A free first-aid course is offered at the community centre.', ['Attend', 'You learn CPR on a dummy named Vasya.', { know: 3, merit: 3, energy: -6 }], ['Skip', 'You hope you never need it.', {}]);
R('hl8', 'health', 'Dentist', 'A tooth hurts when you drink something cold.', ['See a dentist (₽3,500)', 'A small filling and a lecture about flossing.', { money: -3500, health: 3, stress: -4 }], ['Wait and see', 'The tooth becomes a major project later.', { health: -4, stress: 6 }]);
R('hl9', 'health', 'Winter vitamin D', 'The sun disappears in November and you feel gloomy and tired.', ['Take vitamin D and walk in daylight', 'By January you feel human.', { health: 2, stress: -6, money: -400 }], ['Ignore it', 'The grey season feels longer.', { stress: 6, energy: -6 }], { months: [11, 12, 1, 2] });
R('hl10', 'health', 'Counselling hotline', 'A free psychological hotline works day and night.', ['Call and talk for half an hour', 'The voice is kind. You feel lighter.', { stress: -16, know: 1 }], ['Write a letter you do not send', 'Even that helps a little.', { stress: -6 }]);
R('hl11', 'health', 'Quit smoking', 'A friend dares you to stop smoking for a month.', ['Take the challenge', 'The first week is hell; the third week is wonderful.', { health: 4, stress: 6, money: 2000 }], ['Decline', 'You promise to start on Monday.', {}]);
R('hl12', 'health', 'A sports injury', 'You twist your ankle on the ice.', ['Go to the trauma point', 'X-ray, bandage, crutches and a medical note.', { health: -2, money: -500, stress: 3 }], ['Walk it off', 'It gets worse before it gets better.', { health: -6, stress: 6 }], { months: [11, 12, 1, 2, 3] });

/* =================== NEIGHBOURHOOD =================== */
R('nb1', 'home', 'The lift is stuck', 'The lift stops between floors and the emergency button hums.', ['Press the call button and wait', 'A technician arrives in thirty minutes. A neighbour offers sweets to keep your spirits up.', { stress: 6, energy: -4 }], ['Call a neighbour on your phone', 'He laughs: "I am in the same lift!"', { stress: 2, friends: 1 }]);
R('nb2', 'home', 'Noisy repairs', 'Neighbours are drilling at 7 a.m. on Saturday. Quiet hours are officially from 23:00 to 7:00.', ['Knock politely and ask for a break', 'They apologise and finish by noon.', { stress: 3, rep: 1 }], ['Bang on the wall', 'The drilling gets louder.', { stress: 8 }]);
R('nb3', 'home', 'The heating season', 'The radiators are still cold even though it is below zero.', ['Call the management company', 'They promise to switch it on "this week". It is on in two days.', { stress: 4, know: 1 }], ['Use an electric heater', 'Warm but expensive.', { money: -1200, health: 1 }], { months: [9, 10] });
R('nb4', 'home', 'Babushkas on the bench', 'The grandmothers on the bench ask where you are going, who with and whether you have eaten.', ['Stop and chat for five minutes', 'You get a recipe, a warning about the weather and a blessing.', { stress: -8, rep: 3, friends: 1 }], ['Say good morning and walk on', 'They mutter approvingly.', { rep: 1 }]);
R('nb5', 'home', 'Stray cats in the basement', 'Cats live in your building\'s basement. A neighbour feeds them every day.', ['Leave some food', 'A fluffy ginger cat purrs against your leg.', { money: -150, stress: -8, merit: 2 }], ['Walk past', 'The ginger cat judges you.', {}]);
R('nb6', 'home', 'Courtyard football', 'Boys in the courtyard are playing football and ask if you want to join.', ['Play for fifteen minutes', 'You are the goalkeeper and the worst defender.', { energy: -8, stress: -10, friends: 1 }], ['Watch', 'You applaud a spectacular own goal.', { stress: -3 }]);
R('nb7', 'home', 'Waste sorting initiative', 'A group wants to start waste sorting in the courtyard.', ['Join and carry bins', 'Containers appear. The neighbours are proud.', { merit: 5, rep: 3, energy: -8 }], ['Support from your window', 'You cheer them on.', { merit: 1 }]);
R('nb8', 'home', 'A pothole petition', 'Residents are signing a petition about a dangerous pothole near the school.', ['Sign and share it', 'It is fixed within a month. You feel powerful.', { merit: 4, rep: 2 }], ['Walk around the pothole', 'It remains a local landmark.', {}]);
R('nb9', 'home', 'A new neighbour', 'A family moves in across the landing with boxes, a cat and a loud toddler.', ['Bring bread and salt as a welcome', 'It is a custom for new homes: bread for abundance, salt for good luck.', { rep: 3, friends: 1, stress: -4, merit: 1, money: -150 }], ['Say hello in the corridor', 'A polite nod.', { rep: 1 }]);
R('nb10', 'home', 'Snowman contest', 'The management company holds a snowman contest in the courtyard.', ['Build a snowman with the kids', 'Yours has a carrot nose and a scarf. It wins "the most original".', { stress: -12, merit: 2, friends: 1, energy: -6 }], ['Judge the entries from the window', 'You applaud with mittens on.', { stress: -4 }], { months: [12, 1, 2] });
R('nb11', 'home', 'The dvornik', 'The caretaker asks you to move your bike so he can clear the snow.', ['Move it and thank him', 'He grins: "A good tenant."', { rep: 2 }], ['Say you are busy', 'He moves it himself, muttering.', { rep: -2 }], { months: [11, 12, 1, 2, 3] });
R('nb12', 'home', 'A lost parcel', 'A courier left your parcel with a neighbour you have never met.', ['Knock on every door to find it', 'It takes twenty minutes and three cups of tea. You find it in flat 33.', { friends: 1, stress: -2, rep: 2 }], ['Order again', 'Quick, but expensive.', { money: -1200 }]);

/* =================== LIFE EVENTS =================== */
R('le1', 'social', 'Your birthday', 'It is your birthday. Friends ask where the party is.', ['Throw a small party at home', 'Salad, pies and loud laughter. A neighbour knocks at midnight, then joins.', { money: -2500, stress: -14, friends: 2, rep: 3 }], ['Spend the day quietly', 'Tea, a call from home and a slice of cake.', { stress: -4, famLove: 3 }]);
R('le2', 'social', 'A friend\'s wedding', 'You are invited as a guest to a big wedding with a toastmaster and a hundred guests.', ['Go and give a gift envelope (₽5,000)', 'Toasts, dancing and a long table. You cry at the vows.', { money: -5000, stress: -14, friends: 2, merit: 1 }], ['Send your congratulations', 'A warm message and a promise to meet soon.', { money: -1000, friends: -1 }]);
R('le3', 'social', 'A housewarming', 'A friend has moved to a new flat and invites you for a housewarming party.', ['Bring bread, salt and a plant', 'The host says: "Wealth to this house."', { money: -800, rep: 3, stress: -8, friends: 1 }], ['Bring only flowers', 'Warm but simple.', { money: -400, rep: 1 }]);
R('le4', 'social', 'A funeral of a neighbour', 'An elderly neighbour has died. The building gathers to pay respects.', ['Attend and help the family', 'You carry chairs, pour tea and stand silently. The family thanks you.', { stress: 6, rep: 4, merit: 3 }], ['Send condolences', 'A short message. It is received with gratitude.', { rep: 1 }]);
R('le5', 'social', 'First salary', 'The money lands on your card for the first time: a small, real sum.', ['Treat yourself and a friend to dinner', 'You pay the bill with a grin.', { money: -2500, stress: -12, friends: 1 }], ['Save it all', 'You write the number in your notebook.', { stress: -4, know: 1 }]);
R('le6', 'social', 'A breakup', 'A relationship ends with a short message and a long silence.', ['Call a friend and talk', 'You eat dumplings at midnight and cry and laugh.', { stress: -8, friends: 1 }], ['Bury yourself in work', 'It helps, until Sunday.', { stress: 6, energy: -8 }], { req: s => !!s.partner });
R('le7', 'social', 'A school reunion', 'Your old classmates organise a reunion in a café.', ['Go and talk until closing', 'Everyone has changed; nothing has.', { stress: -10, friends: 2, famLove: 2 }], ['Stay away', 'You prefer the memory.', {}], { who: ['citizen'] });
R('le8', 'social', 'A promotion party', 'A colleague has been promoted and brings a cake to the office.', ['Congratulate him warmly', 'He remembers it later when he needs a favour.', { rep: 3, stress: -4 }], ['Feel envious', 'The cake is delicious anyway.', { stress: 4 }]);
R('le9', 'social', 'A retirement', 'A senior colleague is retiring after forty years and the whole office is moved.', ['Give a speech', 'Your voice trembles. People applaud.', { rep: 4, stress: -4, merit: 2 }], ['Sign the card', 'A small message, a big signature.', { rep: 1 }]);
R('le10', 'social', 'Moving day', 'You need to move to a new flat and your friends offer to help for pizza.', ['Accept and organise a team', 'Boxes, tape and a fridge that does not fit through the door. You laugh through it.', { friends: 2, energy: -16, stress: -4, money: -600 }], ['Hire movers (₽6,000)', 'Efficient and silent.', { money: -6000, energy: -4 }]);
R('le11', 'social', 'An anniversary', 'You have been together for a year. A restaurant or a long walk?', ['Dinner at a nice restaurant (₽5,000)', 'Candles, wine and a small gift.', { money: -5000, love: 8, stress: -10 }], ['A long walk and a thermos of tea', 'Simple, warm and perfect.', { love: 6, stress: -8 }], { req: s => !!s.partner });
R('le12', 'social', 'A lottery ticket', 'A neighbour presses a lottery ticket into your hand: "For luck."', ['Scratch it', 'You win ₽100. You buy another one.', { money: 100, stress: -2 }], ['Give it back', 'He shrugs: "Your loss."', {}]);
R('le13', 'social', 'A lost wallet is returned', 'A stranger calls: "I found your wallet. Meet me at the metro."', ['Meet and thank him with a reward', 'Everything is inside. He refuses the reward; you buy him a coffee.', { money: -300, stress: -10, merit: 1, rep: 2 }], ['Ask him to mail it', 'He agrees, but it takes a week.', { stress: 4 }]);
R('le14', 'social', 'You are laid off', 'The manager invites you to his office and offers you tea, which is never a good sign.', ['Ask about severance and references', 'You get two weeks\' pay and a letter of recommendation.', { job: null, money: 4000, stress: 8, rep: 1 }], ['Argue and walk out', 'You leave with nothing and a sore pride.', { job: null, stress: 12, rep: -2 }], { req: s => !!s.job, w: 0.4 });

/* =================== MONEY =================== */
R('mo1', 'shop', 'The 11.11 sale', 'Every marketplace screams "Mega sale!" and your phone buzzes constantly.', ['Buy only what you planned', 'You save 20% on winter boots.', { money: -3600, clothes: 22, know: 1 }], ['Add everything to the cart', 'Your wallet weeps.', { money: -9000, stress: 5 }], { months: [11] });
R('mo2', 'bank', 'A late salary', 'Payday passes and the money has not arrived. The accountant says "Friday".', ['Wait until Friday', 'It arrives on Thursday evening.', { stress: 6 }], ['Remind the manager politely', 'The accountant is annoyed but pays on the same day.', { rep: -1, money: 1000, stress: 2 }], { req: s => !!s.job });
R('mo3', 'bank', 'A pay-raise conversation', 'You think you deserve a raise. The manager is in a good mood after lunch.', ['Ask, with examples of your results', 'He grumbles and agrees to a small raise.', { rep: 3, know: 2, money: 1500 }], ['Wait to be noticed', 'Nobody notices.', { stress: 3 }], { req: s => !!s.job });
R('mo4', 'bank', 'Bank deposit', 'The bank sells you a deposit with a bright pamphlet. The rate looks high.', ['Read the terms and choose carefully', 'You find a fair one with a safe insurance limit.', { know: 3, stress: -2 }], ['Take the first offer', 'The conditions have a catch.', { stress: 3, money: -300 }]);
R('mo5', 'bank', 'A friend asks for a loan', 'A friend asks for ₽5,000 until payday.', ['Lend it', 'He repays on time and buys you a coffee.', { money: -5000, rep: 3, friends: 1 }], ['Refuse politely', 'He understands, mostly.', { friends: -1 }]);
R('mo6', 'bank', 'Crowdfunding for a friend', 'A message circulates: a friend\'s child needs treatment and the family is collecting donations.', ['Donate ₽1,500', 'You are thanked by the whole family.', { money: -1500, merit: 5, rep: 4, stress: -4 }], ['Share the post only', 'The message reaches ten more people.', { merit: 1 }]);
R('mo7', 'shop', 'Tipping etiquette', 'The waiter was excellent. In Russia tipping is about 5–10%.', ['Tip 10%', 'The waiter beams and brings candy.', { money: -250, rep: 2 }], ['Skip the tip', 'He shrugs; you feel a bit mean.', { rep: -1 }]);
R('mo8', 'shop', 'Bargaining at a bazaar', 'A seller at a bazaar names a high price with a charming smile.', ['Haggle with humour', 'You win ₽300 off and a gift of dried apricots.', { money: -1200, stress: -4, know: 1 }], ['Pay the full price', 'He smiles even wider.', { money: -1500 }]);
R('mo9', 'shop', 'Flea market', 'A Saturday flea market offers samovars, records and mysterious cameras.', ['Buy something old and charming', 'A 1970s camera that actually works.', { money: -1500, stress: -8, know: 1 }], ['Just browse', 'You find three things you do not need and buy none.', { stress: -4 }]);
R('mo10', 'shop', 'Loyalty cards', 'The cashier asks: "Do you have our card?" and a queue holds its breath.', ['Say no and move on', 'The cashier sighs with theatrical patience.', {}], ['Sign up for the card', 'Points, coupons and a pile of notifications.', { money: 200, know: 1 }]);
R('mo11', 'bank', 'A utility subsidy', 'You hear that families with low income can apply for a housing subsidy.', ['Apply with income certificates', 'A month later your bills are lower.', { money: 2500, know: 2 }], ['Skip the paperwork', 'Your bills stay high.', {}], { who: ['citizen'] });
R('mo12', 'bank', 'Pension info', 'A relative asks about the pension fund. You read up on how contributions work.', ['Read the official pages', 'You learn a lot and make a plan.', { know: 3, stress: -2 }], ['Leave it for later', 'There is time.', {}]);

/* =================== SEASONS =================== */
R('se1', 'social', 'First snow', 'You wake up to a white world: roofs, trees, benches, all covered.', ['Walk in the first snow', 'Squeaky snow under your boots and a quiet city.', { stress: -12, energy: -2 }], ['Stay under the blanket', 'The window is a postcard.', { energy: 6 }], { months: [10, 11, 12] });
R('se2', 'social', 'Spring thaw', 'The snow turns to puddles and the pavement to a river.', ['Wear waterproof boots', 'You keep your feet dry and your spirits high.', { stress: -4, money: -2500, clothes: 5 }], ['Wear sneakers', 'Soaked within a block.', { health: -3, stress: 4 }], { months: [3, 4] });
R('se3', 'social', 'Birch sap', 'Villagers sell fresh birch sap in plastic bottles by the road.', ['Try a glass', 'Sweet, clear and strange. A taste of spring.', { money: -100, stress: -4 }], ['Pass by', 'Next year.', {}], { months: [3, 4] });
R('se4', 'social', 'A mayovka picnic', 'In May, people grill shashlik in parks and forests; the smell is everywhere.', ['Join a group of colleagues', 'Meat, tea and music from a phone. You come back sunburnt.', { money: -800, friends: 1, stress: -12 }], ['Grill alone on a balcony', 'The neighbours smell it and say nothing.', { stress: -4 }], { months: [5] });
R('se5', 'social', 'Swimming in the lake', 'On a hot day the lake near the city fills with swimmers.', ['Swim', 'Cold, then delicious.', { stress: -12, health: 2 }], ['Sunbathe on the shore', 'A cold drink and a new tan line.', { stress: -8 }], { months: [6, 7, 8] });
R('se6', 'social', 'Thunderstorm', 'A summer thunderstorm rolls over the city; the power flickers.', ['Light candles and watch the storm', 'A small blackout feels like a gift.', { stress: -6 }], ['Check the news for damage', 'Roads flooded but you are fine.', { stress: 3 }], { months: [6, 7, 8] });
R('se7', 'social', 'Golden autumn', 'The leaves turn gold and every park is a postcard.', ['Walk in a park with a thermos', 'You collect maple leaves and a good mood.', { stress: -12, merit: 1 }], ['Stay inside', 'The golden light comes through the curtains anyway.', {}], { months: [9, 10] });
R('se8', 'shop', 'A New Year market', 'Christmas markets pop up with wooden huts, mulled wine and handmade crafts.', ['Browse and buy small gifts', 'You find a hand-painted ornament and a warm scarf.', { money: -1500, clothes: 3, stress: -8 }], ['Drink mulled wine and watch', 'The lights are enough.', { money: -300, stress: -6 }], { months: [12] });
R('se9', 'social', 'Buying the New Year tree', 'The tree market is full of pine and spruce trees and tinsel.', ['Buy a real tree (₽2,000)', 'Your flat smells like a forest for two weeks.', { money: -2000, stress: -8, love: 2 }], ['Use an artificial tree', 'It is easier, if less magical.', { money: -1000 }], { months: [12] });
R('se10', 'social', 'Decorating the courtyard', 'Neighbours put lights and a tree in the courtyard for New Year.', ['Help hang the lights', 'Hot tea afterwards and a courtyard that glows.', { stress: -8, merit: 3, friends: 1 }], ['Watch from the window', 'You enjoy the glow with a warm cup.', { stress: -3 }], { months: [12] });
R('se11', 'social', 'Old New Year', 'On the night of 13–14 January some families celebrate the Old New Year.', ['Join a neighbour\'s table', 'A second New Year with the same salad. Nobody minds.', { stress: -8, friends: 1 }], ['Go to bed early', 'You wake up refreshed.', { energy: 8 }], { months: [1] });
R('se12', 'social', 'A snowstorm day', 'A blizzard shuts the city for a day. Schools are closed and the roads are empty.', ['Stay home with tea and a good book', 'You treat it like a holiday.', { stress: -10, energy: 10 }], ['Go out in the storm', 'You make the first tracks in the new snow.', { stress: -4, health: -2, energy: -8 }], { months: [12, 1, 2] });
R('se13', 'social', 'The white nights', 'In the northern city it does not get dark until almost dawn.', ['Walk along the river at midnight', 'Pink light on the water. Nobody sleeps.', { stress: -12, energy: -10, merit: 1 }], ['Use blackout curtains and sleep', 'Sleep wins.', { energy: 10 }], { months: [6, 7] });
R('se14', 'social', 'Harvest at the dacha', 'A colleague\'s dacha is overflowing with tomatoes and cucumbers.', ['Help harvest for a share', 'You return with three bags and a recipe for pickles.', { energy: -10, stress: -8, money: 500, friends: 1 }], ['Buy vegetables at a shop', 'Pale tomatoes, high prices.', { money: -600 }], { months: [8, 9] });
R('se15', 'social', 'Back-to-school stationery', 'Stationery shops are full of notebooks, pens and bright backpacks.', ['Buy a good notebook and a pen', 'A fresh notebook feels like a new life.', { money: -400, know: 1, stress: -3 }], ['Use your phone for notes', 'It works.', {}], { months: [8, 9] });
