/* Knowledge pack: quizzes and proverbs. Every answer is a well-documented fact. */
import { S, O } from '../../engine';
import type { Outcome } from '../../engine';

// [slug, topic, question, [A, B, C], index of the correct answer, explanation]
type Q = [string, string, string, [string, string, string], number, string];

const QUIZ: Q[] = [
  /* ---- history ---- */
  ['baptism', 'History', 'In which year is the Baptism of Rus, led by Prince Vladimir, traditionally dated?', ['988', '1147', '1240'], 0, 'Prince Vladimir the Great adopted Christianity in 988 and the Baptism of Rus followed.'],
  ['neva', 'History', 'Who led Novgorod forces to victory in the Battle on the Neva in 1240?', ['Alexander Nevsky', 'Dmitry Donskoy', 'Ivan Kalita'], 0, 'The young Prince Alexander won on the Neva and got the name Nevsky.'],
  ['kulikovo', 'History', 'The Battle of Kulikovo in 1380 is linked with which prince?', ['Dmitry Donskoy', 'Yuri Dolgoruky', 'Peter the Great'], 0, 'Dmitry Donskoy led the Russian princes at Kulikovo field.'],
  ['romanov', 'History', 'In which year did the Romanov dynasty begin its rule?', ['1547', '1613', '1721'], 1, 'Mikhail Romanov was elected tsar in 1613, ending the Time of Troubles.'],
  ['empire', 'History', 'In which year did Peter the Great proclaim the Russian Empire?', ['1703', '1721', '1812'], 1, 'After the Great Northern War, in 1721, Peter took the title of Emperor.'],
  ['hermitagefound', 'History', 'In which year is the Hermitage collection traditionally said to have begun under Catherine the Great?', ['1764', '1917', '1547'], 0, 'In 1764 Catherine bought a collection of paintings in Berlin, the start of the Hermitage.'],
  ['borodino', 'History', 'Which great battle of 1812 took place near Moscow on 7 September?', ['Borodino', 'Poltava', 'Kulikovo'], 0, 'Borodino was the bloodiest battle of the 1812 war with Napoleon.'],
  ['serfs', 'History', 'In which year was serfdom abolished by Alexander II?', ['1861', '1905', '1917'], 0, 'The manifesto of 1861 freed millions of peasants from serfdom.'],
  ['ussr', 'History', 'In which year was the Soviet Union formed?', ['1917', '1922', '1941'], 1, 'The USSR was formed in December 1922 and existed until 1991.'],
  ['olympics80', 'History', 'Which city hosted the Summer Olympics in 1980 with a bear cub mascot called Misha?', ['Moscow', 'Leningrad', 'Sochi'], 0, 'The Moscow 1980 Olympics had Misha the bear as mascot, and he floated away in the closing ceremony.'],
  ['tereshkova', 'History', 'Who was the first woman in space?', ['Valentina Tereshkova', 'Svetlana Savitskaya', 'Yelena Kondakova'], 0, 'Valentina Tereshkova flew on Vostok 6 in June 1963.'],
  ['metro', 'History', 'In which year did the Moscow Metro open?', ['1935', '1917', '1961'], 0, 'The first line opened in 1935 and its stations were built as "palaces for the people".'],
  ['msu', 'History', 'Moscow State University was founded in 1755 on the initiative of which scientist?', ['Mikhail Lomonosov', 'Dmitri Mendeleev', 'Ivan Pavlov'], 0, 'Mikhail Lomonosov, polymath, is the founder\'s name behind MSU.'],
  ['peterpaul', 'History', 'Saint Petersburg began with the foundation of which fortress in 1703?', ['Peter and Paul Fortress', 'Kazan Kremlin', 'Pskov Krom'], 0, 'The Peter and Paul Fortress was the first building of the new city.'],
  ['crimeawar', 'History', 'In which century did Saint Basil\'s Cathedral begin to be built?', ['16th', '12th', '19th'], 0, 'It was built between 1555 and 1561 on the order of Ivan the Terrible.'],
  ['victory45', 'History', 'In which year did the Great Patriotic War end in Europe?', ['1945', '1941', '1953'], 0, 'On 9 May 1945 the surrender took effect in Moscow time. Victory Day is a day of memory in many families.'],
  /* ---- science and technology ---- */
  ['pavlov', 'Science', 'Ivan Pavlov won the 1904 Nobel Prize for his work on...', ['The physiology of digestion', 'Radioactivity', 'Gravity'], 0, 'Pavlov studied digestion and discovered conditioned reflexes along the way.'],
  ['tsiolk', 'Science', 'Konstantin Tsiolkovsky is called the father of...', ['Theoretical cosmonautics', 'The periodic table', 'Radio'], 0, 'Tsiolkovsky developed the rocket equation and dreamed of life beyond Earth.'],
  ['korolev', 'Science', 'Sergei Korolev was the chief designer of...', ['The Soviet space programme', 'The Moscow Metro', 'The AK-47'], 0, 'Korolev led the team that launched Sputnik and Gagarin.'],
  ['popov', 'Science', 'Alexander Popov, a Russian physicist, is linked with the invention of...', ['A radio receiver', 'The telephone', 'The refrigerator'], 0, 'Popov demonstrated a radio receiver in 1895 and is honoured on Radio Day, 7 May.'],
  ['ak47', 'Science', 'Which engineer designed the AK-47 assault rifle?', ['Mikhail Kalashnikov', 'Sergei Korolev', 'Igor Sikorsky'], 0, 'Mikhail Kalashnikov designed it in 1947; the museum in Izhevsk tells the story.'],
  ['sikorsky', 'Science', 'Igor Sikorsky, born in Kyiv in the Russian Empire, became famous for...', ['Building a successful helicopter', 'Writing a famous novel', 'Painting icons'], 0, 'Sikorsky built early multi-engine planes in Russia and later a pioneering helicopter in the US.'],
  ['lobach', 'Science', 'Nikolai Lobachevsky is known for...', ['Non-Euclidean geometry', 'The theory of evolution', 'The first telescope'], 0, 'Lobachevsky, who worked in Kazan, created a new geometry.'],
  ['kovalevskaya', 'Science', 'Sofya Kovalevskaya was...', ['One of the first women to hold a university chair in mathematics in Europe', 'The first female cosmonaut', 'The first Russian prime minister'], 0, 'She was a professor in Stockholm in the late 19th century.'],
  ['landau', 'Science', 'Lev Landau won the Nobel Prize in Physics in which year?', ['1962', '1905', '2000'], 0, 'Landau got the 1962 Nobel for his theory of superfluid helium.'],
  ['alferov', 'Science', 'Zhores Alferov, from Vitebsk and St Petersburg, won the 2000 Nobel Prize for work on...', ['Semiconductor heterostructures', 'Antibiotics', 'Space flight'], 0, 'His work underlies LEDs, lasers and modern communications.'],
  ['graphene', 'Science', 'Andre Geim and Konstantin Novoselov, both born in Russia, won the 2010 Nobel for...', ['Graphene', 'The Hubble telescope', 'Vaccines'], 0, 'They isolated graphene: a single atom-thick layer of carbon.'],
  ['mechnikov', 'Science', 'Ilya Mechnikov won the 1908 Nobel Prize in Medicine for work on...', ['Immunity', 'Digestion', 'Genetics of peas'], 0, 'He discovered phagocytosis, how cells fight infection.'],
  ['sakharov', 'Science', 'Andrei Sakharov, a physicist, received which Nobel Prize in 1975?', ['The Peace Prize', 'The Physics Prize', 'The Literature Prize'], 0, 'He was honoured for his human rights work.'],
  ['mend2', 'Science', 'Which element, number 101, is named after Dmitri Mendeleev?', ['Mendelevium', 'Lomonosovium', 'Russium'], 0, 'Mendelevium was named in 1955 in honour of the periodic table\'s author.'],
  /* ---- literature ---- */
  ['gogol', 'Literature', 'Who wrote "Dead Souls" and "The Government Inspector"?', ['Nikolai Gogol', 'Ivan Turgenev', 'Anton Chekhov'], 0, 'Gogol\'s satire still shapes how Russians talk about bureaucracy.'],
  ['lermontov', 'Literature', 'Who wrote "A Hero of Our Time"?', ['Mikhail Lermontov', 'Leo Tolstoy', 'Alexander Pushkin'], 0, 'Lermontov wrote it in 1840 and died in a duel at 26.'],
  ['turgenev', 'Literature', 'Which writer wrote "Fathers and Sons"?', ['Ivan Turgenev', 'Fyodor Dostoevsky', 'Maxim Gorky'], 0, 'Turgenev\'s novel gave the word "nihilist" its literary fame.'],
  ['chekhov', 'Literature', 'Which playwright wrote "The Cherry Orchard" and "Three Sisters"?', ['Anton Chekhov', 'Ivan Goncharov', 'Mikhail Bulgakov'], 0, 'Chekhov was a doctor as well as a writer.'],
  ['bulgakov', 'Literature', 'Who wrote "The Master and Margarita"?', ['Mikhail Bulgakov', 'Boris Pasternak', 'Vladimir Nabokov'], 0, 'Bulgakov wrote it in the 1930s; it was published decades later.'],
  ['pasternak', 'Literature', 'Boris Pasternak won the 1958 Nobel Prize in Literature. Which novel is he most known for?', ['Doctor Zhivago', 'Oblomov', 'The Idiot'], 0, 'Pasternak was also a great poet.'],
  ['sholokhov', 'Literature', 'Which novel earned Mikhail Sholokhov the 1965 Nobel Prize?', ['And Quiet Flows the Don', 'War and Peace', 'Fathers and Sons'], 0, 'It tells the story of Don Cossacks in turbulent years.'],
  ['bunin', 'Literature', 'Who was the first Russian writer to win the Nobel Prize in Literature (1933)?', ['Ivan Bunin', 'Maxim Gorky', 'Leo Tolstoy'], 0, 'Bunin got it while living in exile in France.'],
  ['brodsky', 'Literature', 'Joseph Brodsky, a poet from Leningrad, won the Nobel Prize in Literature in which year?', ['1987', '1958', '1933'], 0, 'Brodsky wrote in Russian and English.'],
  ['krylov', 'Literature', 'Ivan Krylov is famous for his...', ['Fables', 'Operas', 'Landscape paintings'], 0, 'Krylov\'s fables gave Russian dozens of proverbs.'],
  ['goncharov', 'Literature', 'Which novel by Ivan Goncharov features a famously lazy hero?', ['Oblomov', 'Anna Karenina', 'Crime and Punishment'], 0, 'Oblomov spends most of the novel on his sofa.'],
  ['karamazov', 'Literature', 'Which Dostoevsky novel is about three brothers and their father?', ['The Brothers Karamazov', 'The Idiot', 'Demons'], 0, 'It was Dostoevsky\'s last novel, written in 1879–1880.'],
  ['nabokov', 'Literature', 'Which novelist, born in Saint Petersburg, wrote "Lolita" in English?', ['Vladimir Nabokov', 'Maxim Gorky', 'Isaac Babel'], 0, 'Nabokov wrote in Russian first and later in English.'],
  ['akhmatova', 'Literature', 'Anna Akhmatova is known as...', ['A great poet of the 20th century', 'A famous ballerina', 'A cosmonaut'], 0, 'Her poem "Requiem" memorialises victims of repression.'],
  /* ---- music, art and theatre ---- */
  ['glinka', 'Arts', 'Mikhail Glinka is often called the father of...', ['Russian classical music', 'The Russian novel', 'Russian cinema'], 0, 'His opera "Ruslan and Lyudmila" is a key landmark.'],
  ['mussorgsky', 'Arts', 'Which work by Modest Mussorgsky is inspired by an exhibition of a friend\'s paintings?', ['Pictures at an Exhibition', 'Swan Lake', 'The Firebird'], 0, 'Mussorgsky wrote it for piano in 1874; Ravel orchestrated it later.'],
  ['rimsky', 'Arts', 'Which suite did Nikolai Rimsky-Korsakov write, based on tales of the Arabian Nights?', ['Scheherazade', 'The Nutcracker', 'Giselle'], 0, 'It is a favourite of concert halls worldwide.'],
  ['rach', 'Arts', 'Sergei Rachmaninoff was famous as a composer and as a...', ['Pianist', 'Painter', 'Chess champion'], 0, 'He wrote four piano concertos and was a brilliant performer.'],
  ['stravinsky', 'Arts', 'Which ballet by Igor Stravinsky premiered in Paris in 1910?', ['The Firebird', 'Swan Lake', 'Coppélia'], 0, 'It was Stravinsky\'s breakthrough for the Ballets Russes.'],
  ['prokofiev', 'Arts', 'Sergei Prokofiev composed a musical tale to teach children about the orchestra. What is it?', ['Peter and the Wolf', 'The Nutcracker', 'Cinderella Waltz'], 0, 'Each character is played by a different instrument.'],
  ['shosta', 'Arts', 'Dmitri Shostakovich\'s Seventh Symphony is often called the...', ['Leningrad Symphony', 'Moscow Symphony', 'Siberian Symphony'], 0, 'It was written during the siege of Leningrad.'],
  ['repin', 'Arts', 'Which painting by Ilya Repin shows men pulling a boat along a river?', ['Barge Haulers on the Volga', 'The Ninth Wave', 'Three Bogatyrs'], 0, 'Repin painted it in the early 1870s.'],
  ['malevich', 'Arts', 'Kazimir Malevich is famous for which minimalist 1915 painting?', ['Black Square', 'Barge Haulers', 'The Scream'], 0, 'It became a symbol of abstract art.'],
  ['rublev', 'Arts', 'Andrei Rublev painted which famous icon, now in the Tretyakov Gallery?', ['The Trinity', 'The Mona Lisa', 'The Last Supper'], 0, 'Rublev\'s Trinity is one of the best-known icons in the world.'],
  ['aivazovsky', 'Arts', 'Ivan Aivazovsky is best known as a painter of...', ['The sea', 'Portraits of tsars', 'Winter forests'], 0, '"The Ninth Wave" is his most famous canvas.'],
  ['shishkin', 'Arts', 'Which painter is known for "Morning in a Pine Forest" with bear cubs?', ['Ivan Shishkin', 'Isaac Levitan', 'Vasily Surikov'], 0, 'The bears in the painting were added by Konstantin Savitsky.'],
  ['vasnetsov', 'Arts', 'Viktor Vasnetsov painted "Three Bogatyrs", which are...', ['Heroes of Russian epic tales', 'Three tsars', 'Three seasons'], 0, 'Ilya Muromets, Dobrynya Nikitich and Alyosha Popovich.'],
  ['bolshoi', 'Arts', 'The Bolshoi Theatre is a famous home of ballet and opera in which city?', ['Moscow', 'Kazan', 'Yekaterinburg'], 0, 'Its current building opened in 1825.'],
  ['mariinsky', 'Arts', 'The Mariinsky Theatre is a famous opera and ballet house in which city?', ['Saint Petersburg', 'Moscow', 'Novosibirsk'], 0, 'Tchaikovsky\'s ballets premiered there.'],
  /* ---- geography ---- */
  ['volga', 'Geography', 'Which river is the longest in Europe?', ['The Volga', 'The Danube', 'The Don'], 0, 'The Volga is about 3,500 km long and flows into the Caspian Sea.'],
  ['timezones', 'Geography', 'How many time zones does Russia span?', ['11', '3', '7'], 0, 'From Kaliningrad to Kamchatka Russia spans eleven time zones.'],
  ['ladoga', 'Geography', 'Which lake near Saint Petersburg is the largest in Europe?', ['Lake Ladoga', 'Lake Onega', 'Lake Baikal'], 0, 'Ladoga covers about 17,700 km².'],
  ['oymyakon', 'Geography', 'Oymyakon in Yakutia is known as...', ['The coldest permanently inhabited place on Earth', 'The hottest city in Siberia', 'The largest port'], 0, 'Temperatures there have dropped below −60 °C.'],
  ['geysers', 'Geography', 'The Valley of Geysers, one of the largest geyser fields in the world, is in which region?', ['Kamchatka', 'The Urals', 'Altai'], 0, 'It is part of a UNESCO site on Kamchatka.'],
  ['belukha', 'Geography', 'Mount Belukha is the highest peak of which mountain system?', ['Altai', 'Urals', 'Caucasus'], 0, 'Belukha rises about 4,506 m above the sea.'],
  ['klyuch', 'Geography', 'Klyuchevskaya Sopka is the highest active volcano in...', ['Eurasia', 'Africa', 'South America'], 0, 'It stands about 4,700 metres high on Kamchatka.'],
  ['onega', 'Geography', 'Lake Onega is the second-largest lake in Europe after...', ['Ladoga', 'Baikal', 'Peipus'], 0, 'Both lakes are in northwest Russia.'],
  ['neva2', 'Geography', 'Saint Petersburg stands on which river?', ['The Neva', 'The Volga', 'The Moskva'], 0, 'The Neva is short but wide and flows into the Gulf of Finland.'],
  ['kuril', 'Geography', 'The Kuril Islands stretch between Kamchatka and which island?', ['Hokkaido (Japan)', 'Sakhalin', 'Novaya Zemlya'], 0, 'The island chain curves into the Pacific.'],
  ['lena', 'Geography', 'The Lena Pillars, a UNESCO site, are found in which republic?', ['Sakha (Yakutia)', 'Tatarstan', 'Dagestan'], 0, 'Rock pillars rise along the Lena river.'],
  ['curonian', 'Geography', 'The Curonian Spit, shared by Russia and Lithuania, is a...', ['Narrow sand-dune peninsula on the Baltic', 'Mountain chain', 'Volcanic island'], 0, 'It is a UNESCO site with huge moving dunes.'],
  /* ---- folklore and crafts ---- */
  ['babayaga', 'Folklore', 'In Russian fairy tales, Baba Yaga lives in...', ['A hut on chicken legs', 'A castle in the clouds', 'A boat on a lake'], 0, 'She flies in a mortar and sweeps her tracks with a broom.'],
  ['kolobok', 'Folklore', 'In the fairy tale "Kolobok", a round bun runs away from...', ['Grandma and grandpa, then meets animals', 'A king and a queen', 'A wizard'], 0, 'The tale ends badly for the bun when it meets the fox.'],
  ['dedmoroz', 'Folklore', 'Who accompanies Ded Moroz (Father Frost) at New Year?', ['His granddaughter Snegurochka', 'A bear', 'Baba Yaga'], 0, 'Snegurochka, the Snow Maiden, is a New Year icon.'],
  ['domovoy', 'Folklore', 'A "domovoy" is...', ['A house spirit in Slavic folklore', 'A type of boat', 'A winter hat'], 0, 'People leave him a saucer of milk and ask him to look after the home.'],
  ['gzhel', 'Crafts', 'Gzhel ceramics are known for their...', ['Blue-and-white painting', 'Gold-and-red painting', 'Black glaze'], 0, 'Gzhel comes from a group of villages near Moscow.'],
  ['khokhloma', 'Crafts', 'Khokhloma wooden tableware is known for its...', ['Gold and red floral patterns on a black background', 'Blue-and-white lines', 'Unpainted bare wood'], 0, 'The golden colour comes from tin powder, not gold.'],
  ['palekh', 'Crafts', 'Palekh is known for...', ['Lacquer miniature painting on black boxes', 'Woollen shawls', 'Carved wooden toys'], 0, 'Palekh artists once painted icons.'],
  ['pavlovo', 'Crafts', 'Pavlovo Posad is famous for its...', ['Printed woollen shawls', 'Lacquer trays', 'Painted eggs'], 0, 'The scarves are known for their bright floral patterns.'],
  ['vologda', 'Crafts', 'Vologda is famous for its...', ['Lace', 'Samovars', 'Carpets'], 0, 'Vologda lace is made on bobbins in the northern town.'],
  ['matryoshka2', 'Crafts', 'How many dolls does a classic matryoshka set typically have?', ['Often five to eight', 'Always two', 'Exactly fifty'], 0, 'Sets vary; some have dozens.'],
  /* ---- sport ---- */
  ['summit72', 'Sport', 'The 1972 Summit Series was a famous hockey series between the USSR and...', ['Canada', 'Sweden', 'The United States'], 0, 'It ended in an unforgettable 4–3–1 Canadian victory.'],
  ['kasparov', 'Sport', 'Garry Kasparov became world chess champion in 1985 at what age?', ['22, the youngest ever', '40', '30'], 0, 'Kasparov, born in Baku, beat Anatoly Karpov for the title.'],
  ['sambo', 'Sport', 'Sambo is a martial art that was developed...', ['In the USSR', 'In Japan', 'In Brazil'], 0, 'Its name means "self-defence without weapons" in Russian.'],
  ['isinbayeva', 'Sport', 'Yelena Isinbayeva is a famous champion in which sport?', ['Pole vault', 'Swimming', 'Biathlon'], 0, 'She broke the world record many times.'],
  ['rodnina', 'Sport', 'Irina Rodnina won three Olympic golds in...', ['Pairs figure skating', 'Alpine skiing', 'Fencing'], 0, 'Rodnina skated with two different partners to gold.'],
  ['karelin', 'Sport', 'Alexander Karelin, nicknamed "The Experiment", was a legendary champion in...', ['Greco-Roman wrestling', 'Sambo', 'Boxing'], 0, 'He was unbeaten for thirteen years.'],
  ['sochi14', 'Sport', 'In which year did Sochi host the Winter Olympics?', ['2014', '2010', '2018'], 0, 'Sochi\'s venues are in the Olympic Park and Krasnaya Polyana.'],
  ['zenit', 'Sport', 'Zenit is a football club from...', ['Saint Petersburg', 'Moscow', 'Kazan'], 0, 'It is a famous rival of Moscow teams.'],
  ['tennis', 'Sport', 'Daniil Medvedev won which Grand Slam in 2021?', ['The US Open', 'Wimbledon', 'The French Open'], 0, 'Medvedev beat Novak Djokovic in the final.'],
  /* ---- film and animation ---- */
  ['cheburashka', 'Film', 'Which Soviet cartoon character is a big-eared creature who befriends a crocodile named Gena?', ['Cheburashka', 'Winnie-the-Pooh', 'Kolobok'], 0, 'Cheburashka became a worldwide cultural icon.'],
  ['nupogodi', 'Film', 'In "Nu, pogodi!", which animal chases a hare?', ['A wolf', 'A fox', 'A bear'], 0, 'The cartoon ran from 1969 for many years.'],
  ['irony', 'Film', 'Which comedy do many Russians traditionally watch on New Year\'s Eve?', ['The Irony of Fate', 'Solaris', 'Brother'], 0, 'It was released in 1975 and is still a New Year classic.'],
  ['moscowtears', 'Film', '"Moscow Does Not Believe in Tears" won which award in 1981?', ['An Oscar for Best Foreign Language Film', 'The Palme d\'Or', 'A Golden Bear'], 0, 'It is a romance about three women in Moscow.'],
  ['potemkin', 'Film', '"Battleship Potemkin" (1925) is a landmark film by which director?', ['Sergei Eisenstein', 'Andrei Tarkovsky', 'Nikita Mikhalkov'], 0, 'The Odessa Steps sequence is among the most famous in film history.'],
  ['tarkovsky', 'Film', 'Which sci-fi film was directed by Andrei Tarkovsky in 1972?', ['Solaris', 'Stalker', 'The Mirror'], 0, 'Stalker (1979) is also Tarkovsky\'s; Solaris is the 1972 film.'],
  ['cranes', 'Film', '"The Cranes Are Flying" won the Palme d\'Or at Cannes in which year?', ['1958', '1991', '1975'], 0, 'It is the only Soviet film to win the Palme d\'Or.'],
  ['pooh', 'Film', 'In the 1969 Soviet animation of Winnie-the-Pooh, the director was...', ['Fyodor Khitruk', 'Walt Disney', 'Hayao Miyazaki'], 0, 'Khitruk\'s Pooh is beloved and quite different from Disney\'s.'],
  /* ---- language ---- */
  ['alphabet', 'Language', 'How many letters are in the modern Russian alphabet?', ['33', '26', '29'], 0, 'The Russian alphabet is based on Cyrillic with 33 letters.'],
  ['cases', 'Language', 'How many grammatical cases does Russian have?', ['Six', 'Two', 'Ten'], 0, 'Nominative, genitive, dative, accusative, instrumental and prepositional.'],
  ['dahl', 'Language', 'Vladimir Dahl compiled the famous...', ['Explanatory Dictionary of the Living Great Russian Language', 'Russian grammar', 'Book of fairy tales'], 0, 'Dahl\'s dictionary contains about 200,000 words.'],
  ['mir', 'Language', 'The Russian word "mir" means...', ['Both "peace" and "world"', 'Only "home"', 'Only "bread"'], 0, 'It is the same word used in "War and Peace" (Voyna i mir).'],
  ['sputnik2', 'Language', 'The word "sputnik" originally means...', ['Travelling companion', 'Rocket', 'Star'], 0, 'Sputnik is "fellow traveller", which is how the first satellite got its name.'],
  ['spasibo', 'Language', 'The word "spasibo" ("thank you") is commonly explained as coming from...', ['"Spasi Bog" — "God save"', '"Spas" — "salvation" only', 'A Tatar word'], 0, 'The shortening of "Spasi Bog" is the widely accepted etymology.'],
  ['official', 'Language', 'Besides Russian, many republics of Russia have their own...', ['Co-official languages', 'Separate currencies', 'Time zones only'], 0, 'Examples: Tatar in Tatarstan, Bashkir in Bashkortostan, Chechen in Chechnya.'],
  ['yo', 'Language', 'The letter Ё in Russian is often written as...', ['Е without dots', 'Я', 'Ю'], 0, 'In everyday writing the dots are often omitted, which sometimes changes the meaning.'],
];
QUIZ.forEach(([slug, topic, q, opts, correct, fact]) => S({
  id: `kq-${slug}`, cat: 'culture', w: 0.9, title: `${topic}: a question from a neighbour`, text: q,
  choices: opts.map((o, i) => ({ t: o, r: (): Outcome => (i === correct ? O(`Correct! ${fact}`, { know: 3, merit: 3, stress: -3 }) : O(`Not quite. ${fact}`, { know: 1, merit: 1 })) })),
}));

/* ---------- proverbs ---------- */
// [Russian, transliteration, meaning]
const PROVERBS: [string, string, string][] = [
  ['Семь раз отмерь, один раз отрежь', 'Sem raz otmer, odin raz otrezh', 'measure seven times, cut once: think before you act'],
  ['Утро вечера мудренее', 'Utro vechera mudrenee', 'the morning is wiser than the evening: sleep on it'],
  ['Без труда не вытащишь и рыбку из пруда', 'Bez truda ne vytashchish i rybku iz pruda', 'you cannot even pull a fish from a pond without effort'],
  ['Яблоко от яблони недалеко падает', 'Yabloko ot yabloni nedaleko padaet', 'the apple does not fall far from the tree'],
  ['В гостях хорошо, а дома лучше', 'V gostyakh khorosho, a doma luchshe', 'visiting is good, but home is better'],
  ['Старый друг лучше новых двух', 'Staryy drug luchshe novykh dvukh', 'an old friend is better than two new ones'],
  ['Курочка по зёрнышку клюёт', 'Kurochka po zyornyshku klyuyot', 'a hen pecks grain by grain: small steps add up'],
  ['Волков бояться — в лес не ходить', 'Volkov boyatsya — v les ne khodit', 'if you fear wolves, do not go to the forest: no risk, no gain'],
  ['Тише едешь — дальше будешь', 'Tishe edesh — dalshe budesh', 'the slower you go, the further you get'],
  ['Любишь кататься — люби и саночки возить', 'Lyubish katatsya — lyubi i sanochki vozit', 'if you like to ride, be ready to pull the sled'],
  ['Дарёному коню в зубы не смотрят', 'Daryonomu konyu v zuby ne smotryat', 'do not look a gift horse in the mouth'],
  ['Не всё то золото, что блестит', 'Ne vsyo to zoloto, chto blestit', 'all that glitters is not gold'],
  ['Под лежачий камень вода не течёт', 'Pod lezhachiy kamen voda ne techyot', 'water does not flow under a lying stone: act to get results'],
  ['Лучше поздно, чем никогда', 'Luchshe pozdno, chem nikogda', 'better late than never'],
  ['Как аукнется, так и откликнется', 'Kak aukhnetsya, tak i otklikhnetsya', 'what you shout is what you hear back: you get what you give'],
  ['Что посеешь, то и пожнёшь', 'Chto poseyesh, to i pozhnyosh', 'you reap what you sow'],
  ['Один в поле не воин', 'Odin v pole ne voin', 'one man alone in the field is not a warrior: unity is strength'],
  ['Первый блин комом', 'Pervyy blin komom', 'the first pancake is always a lump: beginners make mistakes'],
  ['Не имей сто рублей, а имей сто друзей', 'Ne imey sto rubley, a imey sto druzey', 'better a hundred friends than a hundred roubles'],
  ['Утопающий хватается за соломинку', 'Utopayushchiy khvatayetsya za solominku', 'a drowning man clutches at a straw'],
  ['Глаза боятся, а руки делают', 'Glaza boyatsya, a ruki delayut', 'the eyes are afraid, but the hands do it: start and fear fades'],
  ['Дружба дружбой, а служба службой', 'Druzhba druzhboy, a sluzhba sluzhboy', 'friendship is friendship, but work is work'],
  ['Готовь сани летом, а телегу зимой', 'Gotov sani letom, a telegu zimoy', 'prepare the sled in summer and the cart in winter'],
  ['Ум хорошо, а два лучше', 'Um khorosho, a dva luchshe', 'one mind is good, two are better'],
  ['Не плюй в колодец — пригодится воды напиться', 'Ne plyuy v kolodets — prigoditsya vody napitsya', 'do not spit in the well: you may need its water'],
  ['Тяжело в учении — легко в бою', 'Tyazhelo v uchenii — legko v boyu', 'hard in training, easy in battle'],
  ['Если хочешь быть здоров — закаляйся', 'Yesli khochesh byt zdorov — zakalyaysya', 'if you want to be healthy, harden yourself'],
  ['Мал золотник, да дорог', 'Mal zolotnik, da dorog', 'small but precious'],
  ['Дело мастера боится', 'Delo mastera boitsya', 'the job is afraid of the master: a skilled person handles it'],
  ['Своя ноша не тянет', 'Svoya nosha ne tyanet', 'your own load is not heavy'],
  ['Без хозяина дом — сирота', 'Bez khozyaina dom — sirota', 'a house without a master is an orphan'],
  ['Где родился, там и пригодился', 'Gde rodilsya, tam i prigodilsya', 'where you were born is where you are useful'],
  ['Новая метла по-новому метёт', 'Novaya metla po-novomu metyot', 'a new broom sweeps in a new way'],
  ['Мороз не велик, да стоять не велит', 'Moroz ne velik, da stoyat ne velit', 'the frost is not big, but it does not let you stand still'],
  ['Не в деньгах счастье', 'Ne v dengakh schastye', 'happiness is not in money'],
  ['Хлеб — всему голова', 'Khleb — vsemu golova', 'bread is the head of everything'],
  ['Русская зима — не лето', 'Russkaya zima — ne leto', 'a Russian winter is not summer: dress for the weather'],
  ['Гость на порог — счастье в дом', 'Gost na porog — schastye v dom', 'a guest at the threshold brings happiness to the home'],
  ['Век живи — век учись', 'Vek zhivi — vek uchis', 'live a century, learn a century'],
  ['Терпение и труд всё перетрут', 'Terpeniye i trud vsyo peretrut', 'patience and work will wear everything down'],
];
PROVERBS.forEach(([ru, tr, mean], i) => {
  S({ id: `prov-${i}-hear`, cat: 'culture', w: 0.7, title: `A proverb: ${ru}`, text: `An older colleague says: "${ru}" (${tr}). It means: ${mean}.`,
    choices: [
      { t: 'Ask her to explain more', r: (): Outcome => O('She tells you three stories about when it came true. You write the proverb down.', { know: 3, merit: 1, stress: -3, friends: 0 }) },
      { t: 'Nod politely', r: (): Outcome => O('You nod. The meaning sinks in later on the bus.', { know: 1 }) },
    ] });
  S({ id: `prov-${i}-use`, cat: 'social', w: 0.5, title: `Use the proverb: ${tr}`, text: `A friend is stuck on a decision. You remember the proverb "${ru}": ${mean}.`,
    choices: [
      { t: 'Share the proverb and add your own example', r: (): Outcome => O('Your friend laughs, then goes quiet, then decides. "You sound like my grandmother," she says, pleased.', { rep: 3, know: 1, stress: -4, friends: 1 }) },
      { t: 'Just listen', r: (): Outcome => O('Sometimes people do not need advice. She thanks you for listening.', { rep: 2, stress: -3 }) },
    ] });
});
